spring:
  application:
    name: itoken-config
  boot:
    admin:
      client:
        url: http://localhost:8084   #服务监控中心配置
  cloud:
    config:
      label: master
      server:
        git:
          uri: git@github.com:ZHXZDN/itoken-config.git
          search-paths: itoken-config/respo
          username: ZHXZDN
          password: a1215386652
  zipkin:
    base-url: http://localhost:9411   #服务链路追踪配置

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info  #监控中心 健康检查